name: depression
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  cloud_functions: ^3.2.5
  equatable: ^2.0.3
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  google_nav_bar: ^5.0.5
  infinite_scroll_pagination: ^3.1.0
  flutter_tags_x: ^1.0.0
  go_router: ^3.0.1
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.12
  sizer: ^2.0.15
  multiavatar: ^0.1.5
  flutter_svg: ^1.0.3

  authentication_repository:
    path: packages/authentication_repository/
  post_repository:
    path: packages/post_repository/

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
