name: post_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_functions: ^3.2.5
  equatable: ^2.0.3
  firebase_core: ^1.11.0
  firebase_remote_config: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0